# Generated by Django 2.1.1 on 2018-10-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('trial_title', models.CharField(max_length=100)),
                ('trial_organiser', models.CharField(max_length=100)),
                ('trial_operator', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('discription', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('operator', models.CharField(max_length=100)),
                ('organiser', models.CharField(max_length=100)),
            ],
        ),
    ]
