# Generated by Django 2.1 on 2018-10-09 07:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='discription',
            field=tinymce.models.HTMLField(),
        ),
    ]
