# Generated by Django 2.1 on 2018-10-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0002_auto_20181009_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('email_list', models.CharField(max_length=500)),
            ],
        ),
    ]
