# Generated by Django 2.1 on 2018-10-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0003_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
